version: "3.7"
services:
  client:
    build:
      context: client/
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./client:/project

  api:
    build:
      context: api/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./api:/project
    environment:
      - DJANGO_SETTINGS_MODULE=bcloud_registry.settings.base

  postgres:
    image: postgres:12.2-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bcloud_registry
      - POSTGRES_USER=bcloud_registry
      - POSTGRES_DB=bcloud_registry

volumes:
  db:
